### ISSUE TITLE
Restructure rule configs to remove validation_config object.

### ISSUE THREAD

**Issue by varunmittal91** [finopsfoundation/focus-spec-validator#69]
Implement a simple structure bringing check to parent level.

```yaml
check_id: FV-D004
dimension: Provider
check:
  data_type: string
```

```yaml
check_id: FV-D004-0001
dimension: Provider
check_friendly_name: "Provider cannot accept null values."
check:
  allow_nulls: false
```
